name: Lint Markdown Links PR
run-name: ${{github.event.pull_request.title}}
on:
  # This workflow is triggered by workflow controller.
  workflow_call:
jobs:
  markdown-link-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Test Infra 
        id: checkout
        uses: actions/checkout@v4
        with:
          repository: kyma-project/test-infra
          ref: main
          path: test-infra

      - name: Checkout PR code
        uses: test-infra/.github/actions/checkout

      - name: Install node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22.x'
      - name: Install md-check-link
        run: npm install -g md-check-link
      - name: Verify links
        run: |
          md-check-link -q -n 8 -c https://raw.githubusercontent.com/kyma-project/md-check-link/main/.mlc.config.json ./