name: pull-validate-dockerfiles

on:
  # This workflow is triggered by workflow controller.
  workflow_call:

jobs:
  hadolint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Test Infra 
        id: checkout
        uses: actions/checkout@v4
        with:
          repository: kyma-project/test-infra
          ref: main
          path: test-infra

      - name: Checkout PR code
        uses: test-infra/.github/actions/checkout

      - name: Lint Dockerfiles
        uses: hadolint/hadolint-action@v3.1.0
        with:
          dockerfile: "Dockerfile"
          recursive: true
