name: pull-go-lint

on:
  # This workflow is triggered by workflow controller.
  workflow_call:
    

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Test Infra 
        id: checkout
        uses: actions/checkout@v4
        with:
          repository: kyma-project/test-infra
          ref: main
          path: test-infra

      - name: Checkout PR code
        uses: test-infra/.github/actions/checkout

      - name: Set up Go
        uses: actions/setup-go@v5

      - uses: golangci/golangci-lint-action@v8.0.0