name: pull-unit-test-go

on:
  # This workflow is triggered by workflow controller.
  workflow_call:

jobs:
  unittest:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Test Infra 
        id: checkout
        uses: actions/checkout@v4
        with:
          repository: kyma-project/test-infra
          ref: main
          path: test-infra

      - name: Checkout PR code
        uses: test-infra/.github/actions/checkout
        
      - uses: actions/setup-go@v5
      - run: go test -cover ./...